environment:
  machine: 192.168.99.101
    port: ${server.port}
  discovery-server:
    port: 8761
  mysql-server:
    port: 3306
  authorization-server:
    port: 7171

eureka:
  instance:
    instance-id: ${spring.application.name}
    hostname: ${environment.machine}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${environment.discovery-server.port}/eureka/

spring:
  datasource:
    url: jdbc:mysql://${environment.machine}:${environment.mysql-server.port}/rent_customer?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

security:
  oauth2:
    resource:
      token-info-uri: http://${environment.machine}:${environment.authorization-server.port}/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin