environment:
  machine: localhost

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${environment.machine}:${server.port}/eureka
  datacenter: Mumbai-India
  environment: development