environment:
  machine: localhost
  discovery-server:
    port: 8761
  mysql-server:
    machine: 127.0.0.1
    port: 3306
  authorization-server:
    port: 7171

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: ${environment.machine}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${environment.discovery-server.port}/eureka

spring:
  cloud:
    kubernetes:
      enabled: false
  datasource:
    url: jdbc:mysql://${environment.mysql-server.machine}:${environment.mysql-server.port}/rent_product?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

security:
  oauth2:
    resource:
      token-info-uri: http://${environment.machine}:${environment.authorization-server.port}/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

management:
  endpoints:
    web:
      exposure:
        include: "*"