database: mysql

spring:
  cloud:
    kubernetes:
      enabled: true
  datasource:
    initialization-mode: always
    url: jdbc:mysql://34.71.210.229/k8_rent_authDB?useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

dekorate:
  kubernetes:
    serviceType: "LoadBalancer"
    expose: true

logging:
  level:
    org:
      hibernate:
        type: trace